-- MySQL Script generated by MySQL Workbench
-- Tue Jan 10 02:02:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shenzhouyinji
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shenzhouyinji
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shenzhouyinji` DEFAULT CHARACTER SET utf8 ;
USE `shenzhouyinji` ;

-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user` (
  `id` VARCHAR(45) NOT NULL,
  `wechat` VARCHAR(45) NULL,
  `login_id` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`notification` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`notification` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `category_id` VARCHAR(45) NULL,
  `content` VARCHAR(1024) NULL,
  `sender` VARCHAR(45) NULL,
  `release_time` INT NULL,
  `blocking_time` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`sys_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`sys_category` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`sys_category` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `parent_id` VARCHAR(45) NULL,
  `has_subclass` TINYINT NULL,
  `status` INT NULL,
  `sort` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`scenery_spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`scenery_spot` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`scenery_spot` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(256) NULL,
  `address` VARCHAR(256) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `coordinate` VARCHAR(256) NULL,
  `electric_fence` VARCHAR(256) NULL,
  `Introduction` TEXT NULL,
  `category_id` VARCHAR(45) NULL,
  `position_tolerance` VARCHAR(256) NULL,
  `passport_link` VARCHAR(256) NULL,
  `health_code_link` VARCHAR(256) NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`scenery_spot_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`scenery_spot_service` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`scenery_spot_service` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(256) NULL,
  `category_id` VARCHAR(45) NULL,
  `address` VARCHAR(256) NULL,
  `images` VARCHAR(1024) NULL,
  `coordinate` VARCHAR(256) NULL,
  `introduction` TEXT NULL,
  `expense_instruction` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_scenery_spot_service_scenery_spot1_idx` (`sceneryspot_id` ASC) VISIBLE,
  CONSTRAINT `fk_scenery_spot_service_scenery_spot1`
    FOREIGN KEY (`sceneryspot_id`)
    REFERENCES `shenzhouyinji`.`scenery_spot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`sys_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`sys_tag` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`sys_tag` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `category_id` VARCHAR(45) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`event` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`event` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(256) NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `images` VARCHAR(1024) NULL,
  `step` VARCHAR(256) NULL,
  `introduction` TEXT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`camp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`camp` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`camp` (
  `id` VARCHAR(45) NOT NULL,
  `event_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `introduction` TEXT NULL,
  `images` VARCHAR(1024) NULL,
  `points` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_camp_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_camp_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `shenzhouyinji`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`honour`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`honour` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`honour` (
  `id` VARCHAR(45) NOT NULL,
  `camp_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `images` VARCHAR(1024) NULL,
  `min_points` INT NULL,
  `max_points` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_honour_camp1_idx` (`camp_id` ASC) VISIBLE,
  CONSTRAINT `fk_honour_camp1`
    FOREIGN KEY (`camp_id`)
    REFERENCES `shenzhouyinji`.`camp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`badge` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`badge` (
  `id` VARCHAR(45) NOT NULL,
  `event_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `images` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_badge_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_badge_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `shenzhouyinji`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`passport_set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`passport_set` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`passport_set` (
  `id` VARCHAR(45) NOT NULL,
  `event_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `status` INT NULL,
  `quantity` INT NULL,
  `issued` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passport_set_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_passport_set_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `shenzhouyinji`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`conversation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`conversation` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`conversation` (
  `id` VARCHAR(45) NOT NULL,
  `participant` VARCHAR(256) NULL,
  `from` VARCHAR(45) NULL,
  `to` VARCHAR(45) NULL,
  `content` VARCHAR(1024) NULL,
  `send_time` INT NULL,
  `read_time` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`question_bank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`question_bank` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`question_bank` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NULL,
  `question` VARCHAR(1024) NULL,
  `options` TEXT NULL,
  `answer` VARCHAR(45) NULL,
  `points` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_badge_swap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_badge_swap` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_badge_swap` (
  `id` VARCHAR(45) NOT NULL,
  `badge_id` VARCHAR(45) NULL,
  `from` VARCHAR(45) NULL,
  `to` VARCHAR(45) NULL,
  `previous_id` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `content` VARCHAR(1024) NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_badge` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_badge` (
  `user_id` VARCHAR(45) NOT NULL,
  `badge_id` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_badge_badge1_idx` (`badge_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_badge_badge1`
    FOREIGN KEY (`badge_id`)
    REFERENCES `shenzhouyinji`.`badge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`tweet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`tweet` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`tweet` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NULL,
  `content` JSON NULL,
  `like` JSON NULL,
  `share` JSON NULL,
  `viewed` JSON NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`passport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`passport` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`passport` (
  `id` VARCHAR(45) NOT NULL,
  `passport_set_id` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passport_passport_set1_idx` (`passport_set_id` ASC) VISIBLE,
  CONSTRAINT `fk_passport_passport_set1`
    FOREIGN KEY (`passport_set_id`)
    REFERENCES `shenzhouyinji`.`passport_set` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`stamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`stamp` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`stamp` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(256) NULL,
  `coordinate` VARCHAR(256) NULL,
  `code` VARCHAR(45) NULL,
  `images` VARCHAR(1024) NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_stamp_scenery_spot1_idx` (`sceneryspot_id` ASC) VISIBLE,
  CONSTRAINT `fk_stamp_scenery_spot1`
    FOREIGN KEY (`sceneryspot_id`)
    REFERENCES `shenzhouyinji`.`scenery_spot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`trek_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`trek_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`trek_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `step` INT NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`screenshot_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`screenshot_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`screenshot_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`puzzle_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`puzzle_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`puzzle_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`followers` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`followers` (
  `user_id` VARCHAR(45) NOT NULL,
  `follower` VARCHAR(45) NOT NULL,
  `follower_time` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `follower`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`sys_config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`sys_config` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`sys_config` (
  `id` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(1024) NULL,
  `advertisement` VARCHAR(1024) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_ claim_code`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_ claim_code` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_ claim_code` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_ claim_code_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_ claim_code_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `shenzhouyinji`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`geocaching_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`geocaching_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`geocaching_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`camp_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`camp_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`camp_task` (
  `camp_id` VARCHAR(45) NOT NULL,
  `task_id` VARCHAR(45) NOT NULL,
  `task_type` VARCHAR(45) NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  PRIMARY KEY (`camp_id`, `task_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_stamp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_stamp` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_stamp` (
  `stamp_id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `claim_time` INT NULL,
  INDEX `fk_user_stamp_stamp1_idx` (`stamp_id` ASC) VISIBLE,
  PRIMARY KEY (`stamp_id`, `user_id`),
  CONSTRAINT `fk_user_stamp_stamp1`
    FOREIGN KEY (`stamp_id`)
    REFERENCES `shenzhouyinji`.`stamp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`scenery_spot_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`scenery_spot_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`scenery_spot_task` (
  `task_id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `task_type` VARCHAR(45) NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  PRIMARY KEY (`task_id`, `sceneryspot_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_notification` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_notification` (
  `user_id` VARCHAR(45) NOT NULL,
  `notification_id` VARCHAR(45) NOT NULL,
  `status` INT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_notification_notification1_idx` (`notification_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_notification_notification1`
    FOREIGN KEY (`notification_id`)
    REFERENCES `shenzhouyinji`.`notification` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_unread_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_unread_message` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_unread_message` (
  `user_id` VARCHAR(45) NOT NULL,
  `notification_count` INT NULL,
  `message_count` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_camp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_camp` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_camp` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `camp_id` VARCHAR(45) NOT NULL,
  `honour` VARCHAR(45) NULL,
  `points` INT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  INDEX `fk_user_camp_camp1_idx` (`camp_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_camp_camp1`
    FOREIGN KEY (`camp_id`)
    REFERENCES `shenzhouyinji`.`camp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_task` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `task_id` VARCHAR(45) NOT NULL,
  `task_type` VARCHAR(45) NULL,
  `result` TEXT NULL,
  `points` INT NULL,
  `status` INT NULL,
  `audit` VARCHAR(45) NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_scenery_spot_task_scenery_spot_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_scenery_spot_task_scenery_spot_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `shenzhouyinji`.`scenery_spot_task` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_camp_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_camp_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_camp_task` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `camp_id` VARCHAR(45) NOT NULL,
  `task_id` VARCHAR(45) NOT NULL,
  `result` TEXT NULL,
  `points` INT NULL,
  `status` INT NULL,
  `audit` VARCHAR(45) NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_camp_task_camp_task1_idx` (`camp_id` ASC, `task_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_camp_task_camp_task1`
    FOREIGN KEY (`camp_id` , `task_id`)
    REFERENCES `shenzhouyinji`.`camp_task` (`camp_id` , `task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_profile` (
  `id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `age` INT NULL,
  `birthday` INT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `tags` VARCHAR(45) NULL,
  `nric` VARCHAR(45) NULL,
  `authentication` TINYINT NULL,
  `profession` VARCHAR(45) NULL,
  `guardian_name` VARCHAR(45) NULL,
  `guardian_nric` VARCHAR(45) NULL,
  `guardian_phone` VARCHAR(45) NULL,
  `create_time` INT NULL,
  INDEX `fk_user_profile_user1_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile_user1`
    FOREIGN KEY (`id`)
    REFERENCES `shenzhouyinji`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_tweet_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_tweet_status` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_tweet_status` (
  `user_id` VARCHAR(45) NOT NULL,
  `follower_count` INT NULL,
  `following_count` INT NULL,
  `tweet_count` INT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`event_scenery_spot`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`event_scenery_spot` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`event_scenery_spot` (
  `event_id` VARCHAR(45) NOT NULL,
  `scenery_spot_id` VARCHAR(45) NOT NULL,
  INDEX `fk_event_scenery_spot_event1_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_scenery_spot_event1`
    FOREIGN KEY (`event_id`)
    REFERENCES `shenzhouyinji`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`user_passport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`user_passport` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`user_passport` (
  `id` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `passport_id` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NULL,
  `claim_time` INT NULL,
  `status` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passport_copy1_passport1_idx` (`passport_id` ASC) VISIBLE,
  CONSTRAINT `fk_passport_copy1_passport1`
    FOREIGN KEY (`passport_id`)
    REFERENCES `shenzhouyinji`.`passport` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`following`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`following` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`following` (
  `user_id` VARCHAR(45) NOT NULL,
  `following` VARCHAR(45) NOT NULL,
  `following_time` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`, `following`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`screenshot_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`screenshot_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`screenshot_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`puzzle_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`puzzle_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`puzzle_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `points` INT NULL,
  `images` VARCHAR(1024) NULL,
  `introduction` TEXT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `necessary` TINYINT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`question_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`question_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`question_task` (
  `id` VARCHAR(45) NOT NULL,
  `sceneryspot_id` VARCHAR(45) NOT NULL,
  `questions` TEXT NOT NULL,
  `start_time` INT NULL,
  `end_time` INT NULL,
  `points` INT NULL,
  `status` INT NULL,
  `create_time` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shenzhouyinji`.`question_bank_has_question_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shenzhouyinji`.`question_bank_has_question_task` ;

CREATE TABLE IF NOT EXISTS `shenzhouyinji`.`question_bank_has_question_task` (
  `question_bank_id` VARCHAR(45) NOT NULL,
  `question_task_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`question_bank_id`, `question_task_id`),
  INDEX `fk_question_bank_has_question_task_question_task1_idx` (`question_task_id` ASC) VISIBLE,
  INDEX `fk_question_bank_has_question_task_question_bank1_idx` (`question_bank_id` ASC) VISIBLE,
  CONSTRAINT `fk_question_bank_has_question_task_question_bank1`
    FOREIGN KEY (`question_bank_id`)
    REFERENCES `shenzhouyinji`.`question_bank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_bank_has_question_task_question_task1`
    FOREIGN KEY (`question_task_id`)
    REFERENCES `shenzhouyinji`.`question_task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
